---
- name: Configure cloud account with default settings
  hosts: localhost
  gather_facts: false
  collections:
  - ibm.cloudcollection

  tasks:
    - name: Fetch the variables from var file
      ansible.builtin.include_vars:
        file: extra_vars.yml

    - name: Set facts for supplied variables to convert from json
      ansible.builtin.set_fact:
        extra_variables_json: "{{ extra_variables|from_json }}"


    - name: Show all variables
      ansible.builtin.debug:
        msg: 
         - "extra_variables: {{ extra_variables_json }}"
